name: CI
on:
  pull_request:
  push:

jobs:
  main:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.18'
            erlang: '27.2'
            lint: true
          - elixir: '1.17'
            erlang: '26.2.5.6'
          - elixir: '1.16'
            erlang: '25.3.2.16'
            blend: tower_0_7
          - elixir: '1.15'
            erlang: '24.3.4.17'
            blend: plug_1_14
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        if: ${{ ! matrix.lint }}
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.erlang }}-${{ hashFiles('mix.lock') }}
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.erlang }}
          elixir-version: ${{ matrix.elixir }}
      - run: cp blend/${{ matrix.blend }}/mix.lock mix.lock
        if: ${{ matrix.blend }}
      - run: mix deps.get --check-locked
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.unlock --check-unused
      - run: mix compile --warnings-as-errors
      - run: mix test
